name: "Publish Server Release"

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "DisChord Server Release ${{ github.ref_name }}"
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-server:
    needs: publish-release
    uses: DisChord-Org/.github/.github/workflows/notify_server.yml@v1.1
    secrets: inherit
